### ISSUE TITLE
Web socket client connection

### ISSUE THREAD

**Issue by Jannaiz** [Jannaiz/Cosmic-Chess#15]
# Web socket client connection

## Goal
Make a connection to the backend node server through a WebSocket.
The WebSocket system has already been made in #12 by @AtlantiaKing.
The new goals are:
- Make a server connection
- Send your last move to the server
- Receive move from the other player and do it.

## Sending
For sending the data and goal must be specified.
This will be done with a number in front of the message.

## Receiving
The same number system will be used as in sending.
After that, the move will be done on the client-side.
And so the next turn can start.

**Comment by AtlantiaKing** [comment]
Networking V2 added a fully functioning multiplayer chess game using websockets.
