### ISSUE TITLE
Server messages

### ISSUE THREAD

**Issue by AtlantiaKing** [Jannaiz/Cosmic-Chess#25]
A small chat/message box to display server messages such as:

_Client-side:_

- [x]  Receive server messages

_Server-side:_

- [x] Player join messages
- [x] Player ready-up messages
- [x] Player move messages
- [x] Player disconnect messages
- [x] Player forwarded messages (chat, preset player messages, etc.)

**Comment by AtlantiaKing** [comment]
@Jannaiz client-side is done, I only need the server to be updated to test it.

**Comment by Jannaiz** [comment]
Ok, the code for server messages was 7, right?

**Comment by AtlantiaKing** [comment]
> Ok, the code for server messages was 7, right?

Yup, player messages are sent with packetType 7 and server messages are also with packetType 7.
